language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - pytest
after_success:
  - coverage run main.py
  - coverage run app/helpers.py
  - coverage run app/global.py
  - codecov
  - bash <(curl -s https://codecov.io/bash)
