language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - pytest
after_success:
  - coverage run tests/test_api.py
  - coverage run app/helpers.py
  - coverage run app/global.py
  - coverage run packages/indicativeMetrics.py
  - coverage run packages/noDataFound.py
  - coverage run packages/projectionRepositoryCount.py
  - coverage run packages/repositoryCount.py
  - coverage run routes/routeEndpoints.py
  - codecov
  - bash <(curl -s https://codecov.io/bash)
